OnlineStudy/urls.py
# from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib import admin
from django.views.generic import TemplateView


import xadmin
from django.views.static import serve

from users.views import LoginView,  RegisterView, ActiveUserView, ForgetPwdView, ResetView, ModifyPwdView, LogoutView
from users.views import IndexView, page_not_found, page_error
from organization.views import OrgView
from OnlineStudy.settings import MEDIA_ROOT, STATIC_ROOT

urlpatterns = [
       # path('admin/', admin.site.urls),
       path('xadmin/', xadmin.site.urls),
       path('', IndexView.as_view(), name="index"),
       path('login/', LoginView.as_view(), name="login"),
       path('logout/', LogoutView.as_view(), name="logout"),
       path('register/', RegisterView.as_view(), name="register"),
       path('captcha/', include('captcha.urls')),
       path('forget', ForgetPwdView.as_view(), name="forget_pwd"),
       path('modify_pwd', ModifyPwdView.as_view(), name="modify_pwd"),

       path('org/', include('organization.urls', namespace="org")),

       path('course/', include('courses.urls', namespace="course")),

       path('users/', include('users.urls', namespace="users")),




       re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
       re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name="user_active"),
       re_path('media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
       re_path('static/(?P<path>.*)$', serve, {"document_root": STATIC_ROOT}),

]

handler404 = 'users.views.page_not_found'
handler500 = 'users.views.page_error'

apps/courses/urls.py
__author__ = 'wdz'
__date__ = '2019/10/27 19:21'

from django.urls import path, re_path, include
from .views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddComentsView, VideoPlayView

app_name = 'courses'
urlpatterns = [

    path('list/', CourseListView.as_view(), name="course_list"),
    path('add_comment/', AddComentsView.as_view(), name="add_comment"),
    re_path('detail/(?P<course_id>\d+)/', CourseDetailView.as_view(), name="course_detail"),
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name="course_info"),
    re_path('comment/(?P<course_id>\d+)/', CommentsView.as_view(), name="course_comments"),
    re_path('video/(?P<video_id>\d+)', VideoPlayView.as_view(), name='video_play'),






]

apps/organization/urls.py
from django.urls import path, re_path, include

from .views import OrgView, AddUserAskView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView
from .views import AddFavView, TeacherListView, TeacherDetailView
app_name = 'organization'
urlpatterns = [
    path('add_ask/', AddUserAskView.as_view(), name="add_ask"),
    path('list/', OrgView.as_view(), name="org_list"),
    path('add_fav/', AddFavView.as_view(), name="add_fav"),
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name="org_home"),
    re_path('course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"),
    re_path('desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name="org_desc"),
    re_path('org_teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"),
    path('teacher/list/', TeacherListView.as_view(), name='teacher_list'),

    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDetailView.as_view(), name='teacher_detail'),
]

apps/users/urls.py
from django.urls import path, include, re_path


from .views import UserInfoView, UploadImageView, UpdataPwdView, SendEmailCodeView, MyMessageView
from .views import UpdateEmailView, MycourseView, MyFavOrgView, MyFavTeacherView, MyFavCourseView
app_name = 'users'
urlpatterns = [
    # 用户信息
    path('info/', UserInfoView.as_view(), name='user_info'),
    path('image/upload/', UploadImageView.as_view(), name="image_upload"),
    path('update/pwd/', UpdataPwdView.as_view(), name="update_pwd"),

    # send emial verify code
    path('sendemail_code/', SendEmailCodeView.as_view(), name="sendemail_code"),
    path('update_email/', UpdateEmailView.as_view(), name="update_email"),

    path('mycourse/', MycourseView.as_view(), name="mycourse"),
    path('myfav/org', MyFavOrgView.as_view(), name="myfav_org"),
    path('myfav/teacher', MyFavTeacherView.as_view(), name="myfav_teacher"),
    path('myfav/course', MyFavCourseView.as_view(), name="myfav_course"),
    path('mymessage/', MyMessageView.as_view(), name="mymessage")
]

apps/courses/models.py
from datetime import datetime

from django.db import models
from organization.models import CourseOrg, Teacher
# Create your models here.
#Course Model
class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name="course_org", null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, verbose_name="Name")
    desc = models.CharField(max_length=300, verbose_name="Description")
    is_banner = models.BooleanField(default=False, verbose_name="Is_banner")
    detail = models.TextField(verbose_name="Detail")
    teacher = models.ForeignKey(Teacher, verbose_name="Teacher", null=True, blank=True, on_delete=models.CASCADE)
    degree = models.CharField(choices=(("1", "beginner"), ("2", "intermediate"), ("3", "advance")), max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name="learn length(minute)")
    students = models.IntegerField(default=0, verbose_name="StudentNumber")
    fav_nums = models.IntegerField(default=0, verbose_name="Fav_nums")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name="image", max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name="ClickNum")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="Addtime")
    category = models.CharField(default="backend", max_length=20, verbose_name="CourseCategory")
    tag = models.CharField(default="", verbose_name="CourseTag", max_length=10)
    youneed_know = models.CharField(default="", max_length=300, verbose_name="CourseInfo")
    teacher_tell = models.CharField(default="", max_length=300, verbose_name="TeacherTell")
    class Meta:
        verbose_name = "Course"
        verbose_name_plural = "Courses"

    def get_zj_nums(self):
        #get lessons of the course
        return self.lesson_set.all().count()

    def get_learn_users(self):
        return self.usercourse_set.all()[:5]

    def get_course_lesson(self):
        return self.lesson_set.all()

    def __str__(self):
        return self.name

class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="LessonName")
    learn_times = models.IntegerField(default=0, verbose_name="LearnTime")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="Addtime")

    class Meta:
        verbose_name = "Lesson"
        verbose_name_plural = "Lessons"

    def get_lesson_video(self):
        return self.video_set.all()

    def __str__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name="Lesson", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="VideoName")
    add_time = models.DateTimeField(default=datetime.now, verbose_name="Addtime")
    url = models.CharField(max_length=200, verbose_name="Url", default="")
    learn_times = models.IntegerField(default=0, verbose_name="LearnTime")

    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Videos"

    def __str__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name="Course", on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name="Name")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name="File", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="Addtime")

    class Meta:
        verbose_name = "CourseResource"
        verbose_name_plural = "CourseResources"

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Online-Learning{% endblock %}</title>

	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">

    {% block custom_css %}

    {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
    {% if request.user.is_authenticated %}
        <div class="top">
            <div class="wp">

                <div class="personal">
                    <dl class="user fr">
                        <dd>{{ request.user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                        <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                    </dl>
                    <div class="userdetail">
                        <dl>
                            <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            <dd>
                                <h2>{{ request.user.nick_name }}</h2>
                                <p>{{ request.user.username }}</p>
                            </dd>
                        </dl>
                        <div class="btn">
                            <a class="personcenter fl" href="{% url 'users:user_info' %}">My profile</a>
                            <a class="fr" href="{% url 'logout' %}">Log out</a>
                        </div>
                    </div>
                </div>
                <a href="{%  url 'users:mymessage' %}">
                    <div class="msg-num">
                        <span id="MsgNum">{{ request.user.unread_nums }}</span>
                    </div>
                </a>
            </div>
        </div>
    {% else %}
        <div class="top">
            <div class="wp">
                <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Sign Up</a>
                <a style="color:black" class="fr loginbtn" href="{% url 'login' %}">Log In</a>
            </div>
        </div>
    {% endif %}

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl studylogo" src="{% static 'images/study.png' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                            <span class="selectOption" id="jsSelectOption" data-value="course">
                                Courses
                            </span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">Courses</li>
                                <li data-value="org">Universities</li>
                                <li data-value="teacher">Instructors</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="Search for anything"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav" id="navTop">
					<div class="wp">
						<ul>
							<li {% if request.path == '/index' %}class="active"{% endif %}>
                                <a href="{% url 'index' %}">Home</a>
                            </li>

							<li {% if request.path|slice:'7' == '/course' %}class="active"{% endif %}>
								<a href="{% url 'course:course_list' %}">
									Courses<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>

							<li {% if request.path|slice:'12' == '/org/teacher' %}class="active"{% endif %}>
								<a href="{% url 'org:teacher_list' %}">Instructors</a>
							</li>
                            <li {% if request.path|slice:'9' == '/org/list' %}class="active" {% endif %}>
                                <a href="{% url 'org:org_list' %}">Universities</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->

{% block custom_bread %}
<section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Home</a>></li>
            </ul>
        </div>
</section>
{% endblock %}

{% block content %}
{% endblock %}

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href=""><img width="100" height="80" src="{% static 'images/study.png' %}"/></a></li>
					<li class="third"><img class="fl" width="50" height="35" src="{% static 'images/Email.png' %}"/><p class="time">Contact us: service@OnlineLearning.com</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fr">copyright </span>
			</div>
		</div>
	</footer>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %}{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Online-learning{% endblock %}

{% load staticfiles %}

{% block custom_bread %}{% endblock %}

{% block content %}
<div class="banner">
    <div class="wp">
        <div class="fl">
            <div class="imgslide">
                <ul class="imgs">
                    {% for banner in all_banners %}
                    <li>
                            <a href="{% url 'index' %}">
                                <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="unslider-arrow prev"></div>
            <div class="unslider-arrow next"></div>
        </div>

    </div>
</div>




<section>
    <div class="module">
        <div class="wp">
            <div class="module1 eachmod">
                <div class="module1_1 left">
                    <img width="228" height="614" src="/static/images/new/book.jpg"/>
                    <a class="more" href="{% url 'course:course_list' %}">Learn More</a>
                </div>
{#{{ forloop.counter|add:2 }}#}
                    {% for course in courses %}
                    <div class=".module333 box">
                        <a href="{% url 'course:course_detail' course.id %}">
                            <img class="courseImg" src="{{ MEDIA_URL }}{{ course.image }}"/>
                        </a>
                        <div class="des">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <h2 class="courseName" title="{{ course.name }}">{{ course.name }}</h2>
                            </a>
                            <span class="levelList">Level：<i class="key">{{ course.get_degree_display }}</i></span>
                            <span class="levelList">&nbsp;{{ course.students }}&nbsp;students</span>
                        </div>
                        <div class="bottom">
                            <span class="fl" title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>
                            <span class="star fr">&nbsp;&nbsp;&nbsp;{{ course.fav_nums }}</span>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>


{% endblock %}

{% block custom_js %}
<script type="text/javascript" src="{% static 'js/index.js' %}"></script>
{% endblock %}

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}Universities Online-Learning{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %}{% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>
<body>
<section class="headerwrap headerwrap2">
    <header>
		<div  class="header2 header">
 			{% if request.user.is_authenticated %}
                <div class="top">
                <div class="wp">


                    {% if request.user.is_authenticated %}
                        <div class="personal">
                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static "/static/images/top_down.png" %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ request.user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ request.user.nick_name }}</h2>
	                                    <p>{{ request.user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="">My profile</a>
	                                <a class="fr" href="{% url 'logout' %}">Log out</a>
                                </div>
                            </div>
                        </div>
                        <a href="">
                            <div class="msg-num"> <span id="MsgNum">{{ request.user.unread_nums }}</span></div>
                        </a>
                    {% else %}
                        <a style="color:black" class="fr registerbtn" href="{% url 'register' %}">Log In</a>
                        <a style="color:white" class="fr loginbtn" href="{% url 'login' %}">Sign Up</a>
                    {% endif %}

                </div>
            </div>
                {% else %}
                <div class="top">
				<div class="wp">
                    <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">Sign Up</a>
                    <a style="color:black" class="fr loginbtn" href="{% url 'login' %}">Log In</a>
				</div>
			</div>
            {% endif %}

    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
            <div class="head fl">
                <h1>
                    {{ course_org.name }}

                </h1>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}favorited{% else %}favorite{% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>
<section>
	<div class="wp">
		<ul  class="crumbs">
            <li><a href="{% url 'index' %}">Home</a>></li>
			<li><a href="{% url "org:org_list" %}">Courses</a>></li>
			<li>{% block page_path %}University{% endblock %}</li>
		</ul>
	</div>
</section>

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal current_page 'home' %}active2{% endifequal %}"><a href="{% url 'org:org_home' course_org.id %}">University</a></li>
                <li class="{% ifequal current_page 'course' %}active2{% endifequal %}"><a href="{% url 'org:org_course' course_org.id %}">Courses</a></li>
                <li class="{% ifequal current_page 'desc' %}active2{% endifequal %}"><a href="{% url 'org:org_desc' course_org.id %}">Introduction</a></li>
                <li class="{% ifequal current_page 'teacher' %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' course_org.id %}">Instructors</a></li>
			</ul>
		</div>
    {% block right_form %}
    {% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=2023525077&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">


function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url: "{% url "org:add_fav" %}",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == 'The user has not registered'){
                    window.location.href="/login/";
                }else{
                    alert(data.msg)
                }
            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}
$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});
$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: '{% static 'images/' %}',
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['very poor', 'poor', 'general', 'praise', 'very satisfied'],
                    noRatedMsg  : 'Not yet rated!',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);
    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , 'favorite');
        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );
        }else if(type == '11'){
            favPraise($(this), 'pra', 1);
        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );
        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });
    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}
{% block title %}My profile Online-Learning{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Home</a>></li>
                <li><a href="{% url 'users:user_info' %}">My profile</a>></li>
                <li>My Favorite</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>My Favorite</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'users:myfav_org' %}">University</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">Instructors </a></li>
                        <li class="active"><a href="{% url 'users:myfav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for fav_course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' fav_course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ fav_course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' fav_course.id %}"><h2>{{ fav_course.name }}</h2></a>
                                <span class="fl">Duration<i class="key">{{ fav_course.learn_times }}</i></span>
                                <span class="fr">Students{{ fav_course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ fav_course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ fav_course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-fav-org.html
{% extends 'usercenter_base.html' %}
{% block title %}My profile Online-Learning{% endblock %}
{% load staticfiles %}
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">Home</a>></li>
                <li><a href="{% url 'users:user_info' %}">My profile</a>></li>
                <li>My Favorite</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block right_content %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>My Favorite</h1>
                </div>

            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li class="active"><a href="{% url 'users:myfav_org' %}">University</a> </li>
                        <li><a href="{% url 'users:myfav_teacher' %}">Instructors </a></li>
                        <li><a href="{% url 'users:myfav_course' %}">Courses</a></li>
                    </ul>
                </div>
                <div class="messagelist">
                    {% for org in org_list %}
                    <div class="messages butler_list company company-fav-box">
                        <dl class="des fr">
                            <dt>
                                <a href="{% url 'org:org_home' org.id %}">
                                    <img width="160" height="90" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1><a href="{% url 'org:org_home' org.id %}">{{ org.name }}</a></h1>
                                <div class="pic fl" style="width:auto;">

                                    <img src="{% static 'images/authentication.png' %}"/>


                                    <img src="{% static 'images/gold.png' %}"/>

                                </div>
                                <span class="c8 clear">{{ org.address }}</span>
                                <div class="delete jsDeleteFav_org" data-favid="{{ org.id }}"></div>
                            </dd>
                        </dl>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
{% endblock %}